// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6bJKKBfbGMvpUGAMDXVplBxKhKFpOhwQ',
    appId: '1:814700879413:web:f1b818c845907526f75b7c',
    messagingSenderId: '814700879413',
    projectId: 'binodfolio',
    authDomain: 'binodfolio.firebaseapp.com',
    databaseURL: 'https://binodfolio-default-rtdb.firebaseio.com',
    storageBucket: 'binodfolio.firebasestorage.app',
    measurementId: 'G-H06WN0FZD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdH4wDBReRSr8FSV0adhHJMIiRahqAYE',
    appId: '1:814700879413:android:3db6169c6726b17df75b7c',
    messagingSenderId: '814700879413',
    projectId: 'binodfolio',
    databaseURL: 'https://binodfolio-default-rtdb.firebaseio.com',
    storageBucket: 'binodfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlhjfZTePgDUlGucifkaC6o2WG0eAHx0g',
    appId: '1:814700879413:ios:2ca6f861597f0128f75b7c',
    messagingSenderId: '814700879413',
    projectId: 'binodfolio',
    databaseURL: 'https://binodfolio-default-rtdb.firebaseio.com',
    storageBucket: 'binodfolio.firebasestorage.app',
    iosBundleId: 'com.example.portfolioAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlhjfZTePgDUlGucifkaC6o2WG0eAHx0g',
    appId: '1:814700879413:ios:2ca6f861597f0128f75b7c',
    messagingSenderId: '814700879413',
    projectId: 'binodfolio',
    databaseURL: 'https://binodfolio-default-rtdb.firebaseio.com',
    storageBucket: 'binodfolio.firebasestorage.app',
    iosBundleId: 'com.example.portfolioAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6bJKKBfbGMvpUGAMDXVplBxKhKFpOhwQ',
    appId: '1:814700879413:web:cab12bfe7f81a84cf75b7c',
    messagingSenderId: '814700879413',
    projectId: 'binodfolio',
    authDomain: 'binodfolio.firebaseapp.com',
    databaseURL: 'https://binodfolio-default-rtdb.firebaseio.com',
    storageBucket: 'binodfolio.firebasestorage.app',
    measurementId: 'G-KRG4MEVFVT',
  );
}
